import httpx
from app.config import settings


GITHUB_API_BASE = "https://api.github.com"


def _headers(token: str) -> dict:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def create_or_get_skills_repo(token: str, username: str) -> str:
    repo_name = "skillsclaw-skills"
    with httpx.Client() as client:
        # Check if repo exists
        resp = client.get(
            f"{GITHUB_API_BASE}/repos/{username}/{repo_name}",
            headers=_headers(token),
        )
        if resp.status_code == 200:
            return resp.json()["html_url"]

        # Create the repo
        create_resp = client.post(
            f"{GITHUB_API_BASE}/user/repos",
            headers=_headers(token),
            json={
                "name": repo_name,
                "description": "My Claude Code skills generated by SkillsClaw",
                "private": False,
                "auto_init": True,
            },
        )
        create_resp.raise_for_status()
        repo_url = create_resp.json()["html_url"]

        # Create README
        readme_content = (
            "# SkillsClaw Skills\n\n"
            "These Claude Code skills were generated by [SkillsClaw](https://skillsclaw.com).\n\n"
            "## Installation\n\n"
            "```bash\n"
            f"npx claude-skill install github:{username}/{repo_name}\n"
            "```\n"
        )
        _upsert_file(
            client,
            token,
            username,
            repo_name,
            "README.md",
            readme_content,
            "Initialize SkillsClaw skills repository",
        )
        return repo_url


def publish_skill(
    token: str,
    username: str,
    skill_name: str,
    skill_content: str,
    readme_content: str,
) -> str:
    repo_name = "skillsclaw-skills"
    create_or_get_skills_repo(token, username)

    with httpx.Client() as client:
        # Write the SKILL.md file
        _upsert_file(
            client,
            token,
            username,
            repo_name,
            f"skills/{skill_name}/SKILL.md",
            skill_content,
            f"Add skill: {skill_name}",
        )

        # Write a per-skill README
        _upsert_file(
            client,
            token,
            username,
            repo_name,
            f"skills/{skill_name}/README.md",
            readme_content,
            f"Add README for skill: {skill_name}",
        )

    install_command = f"npx claude-skill install github:{username}/{repo_name}/skills/{skill_name}"
    return install_command


def _upsert_file(
    client: httpx.Client,
    token: str,
    username: str,
    repo_name: str,
    path: str,
    content: str,
    message: str,
) -> None:
    import base64

    encoded = base64.b64encode(content.encode("utf-8")).decode("utf-8")
    url = f"{GITHUB_API_BASE}/repos/{username}/{repo_name}/contents/{path}"

    # Check if file exists to get its sha
    get_resp = client.get(url, headers=_headers(token))
    sha = None
    if get_resp.status_code == 200:
        sha = get_resp.json().get("sha")

    payload: dict = {"message": message, "content": encoded}
    if sha:
        payload["sha"] = sha

    put_resp = client.put(url, headers=_headers(token), json=payload)
    put_resp.raise_for_status()


def get_github_user(token: str) -> dict:
    with httpx.Client() as client:
        resp = client.get(
            f"{GITHUB_API_BASE}/user",
            headers=_headers(token),
        )
        resp.raise_for_status()
        return resp.json()


def exchange_code_for_token(code: str) -> str:
    with httpx.Client() as client:
        resp = client.post(
            "https://github.com/login/oauth/access_token",
            data={
                "client_id": settings.GITHUB_CLIENT_ID,
                "client_secret": settings.GITHUB_CLIENT_SECRET,
                "code": code,
            },
            headers={"Accept": "application/json"},
        )
        resp.raise_for_status()
        data = resp.json()
        if "access_token" not in data:
            raise ValueError(f"GitHub OAuth error: {data.get('error_description', data)}")
        return data["access_token"]
